apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "authservice.fullname" . }}
data:
  auth_service_issuer: {{ tpl .Values.issuer . | quote }}
  auth_service_audience: {{ tpl .Values.audience . | quote }}
  auth_service_session_ttl: {{ .Values.sessionTTL | quote }}
