apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "authservice.fullname" . }}
data:
  auth_service_issuer: {{ tpl (required  "An issuer is required" .Values.issuer) . | quote }}
{{- if .Values.audience }}
  auth_service_audience: {{ tpl (default "" .Values.audience) . }}
{{- end }}
  auth_service_session_ttl: {{ .Values.sessionTTL | quote }}
