{{- if .Capabilities.APIVersions.Has "networking.istio.io/v1alpha3" }}
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ include "authservice.fullname" . }}
spec:
  host: {{ include "authservice.fullname" . }}
  trafficPolicy:
    loadBalancer:
      simple: LEAST_REQUEST
{{- end }}