{{- if .Capabilities.APIVersions.Has "networking.istio.io/v1alpha3" }}
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ include "authservice.fullname" . }}-egress
  labels:
    {{- include "authservice.labels" . | nindent 4 }}
spec:
  host: istio-egressgateway.istio-system.svc.cluster.local
  subsets:
  - name: {{ include "authservice.fullname" . }}
{{- end }}