apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "authservice.fullname" . }}-secret
  annotations:
    helm.sh/hook: pre-install
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "delete"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "authservice.fullname" . }}-secret
  annotations:
    helm.sh/hook: pre-install
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "authservice.fullname" . }}-secret
  annotations:
    helm.sh/hook: pre-install
subjects:
  - kind: ServiceAccount
    namespace: {{ .Release.Namespace }}
    name: {{ include "authservice.fullname" . }}-secret
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "authservice.fullname" . }}-secret
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "authservice.fullname" . }}-create-key
  labels:
    {{- include "authservice.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      labels:
        {{- include "authservice.labels" . | nindent 8 }}
        {{- with .Values.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      restartPolicy: Never
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "authservice.fullname" . }}-secret
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/app/bin/auth-service-token", "--output", "/app/conf/auth_service_jwks"]
          env:
            - name: AUTH_SERVICE_SESSION_SECRET
              value: {{ randAlphaNum 32 | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: temporary
              mountPath: /app/conf
      containers:
        - name: kubectl
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "bitnami/kubectl"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - "kubectl"
            - "create"
            - "secret"
            - "generic"
            - {{ include "authservice.fullname" . }}-key
            - "--from-file"
            - "/app/conf/auth_service_jwks"
          volumeMounts:
            - name: temporary
              readOnly: true
              mountPath: /app/conf
      volumes:
        - name: temporary
          emptyDir: {}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "authservice.fullname" . }}-delete-key
  labels:
    {{- include "authservice.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      labels:
        {{- include "authservice.labels" . | nindent 8 }}
        {{- with .Values.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      restartPolicy: Never
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "authservice.fullname" . }}-secret
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: kubectl
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "bitnami/kubectl"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - "kubectl"
            - "delete"
            - "secret"
            - {{ include "authservice.fullname" . }}-key
