apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "authservice.fullname" . }}
  labels:
    {{- include "authservice.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "authservice.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
  egress: []
