{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace (include "authservice.fullname" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "authservice.fullname" . }}
type: Opaque
data:
{{- if .Values.githubClientId }}
  github_client_id: {{ .Values.githubClientId | b64enc | quote }}
{{- else if $existingSecret }}
  github_client_id: {{ index $existingSecret.data "github_client_id" | quote }}
{{- else }}
  github_client_id: ""
{{- end }}
{{- if .Values.githubClientSecret }}
  github_client_secret: {{ .Values.githubClientSecret | b64enc | quote }}
{{- else if $existingSecret }}
  github_client_secret: {{ index $existingSecret.data "github_client_secret" | quote }}
{{- else }}
  github_client_secret: ""
{{- end }}
{{- if .Values.googleClientId }}
  google_client_id: {{ .Values.googleClientId | b64enc | quote }}
{{- else if $existingSecret }}
  google_client_id: {{ index $existingSecret.data "google_client_id" | quote }}
{{- else }}
  google_client_id: ""
{{- end }}
{{- if .Values.googleClientSecret }}
  google_client_secret: {{ .Values.googleClientSecret | b64enc | quote }}
{{- else if $existingSecret }}
  google_client_secret: {{ index $existingSecret.data "google_client_secret" | quote }}
{{- else }}
  google_client_secret: ""
{{- end }}
{{- if .Values.sessionSecret }}
  session_secret: {{ .Values.sessionSecret | b64enc | quote }}
{{- else if $existingSecret }}
  session_secret: {{ index $existingSecret.data "session_secret" | quote }}
{{- else }}
  session_secret: {{ randAlphaNum 32 | b64enc | quote }}
{{- end }}
