{{- if .Capabilities.APIVersions.Has "networking.istio.io/v1alpha3" }}
apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: {{ include "authservice.fullname" . }}
  labels:
    {{- include "authservice.labels" . | nindent 4 }}
spec:
  hosts:
  {{- toYaml .Values.istio.egressHosts | nindent 2 }}
  location: MESH_EXTERNAL
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  resolution: DNS
{{- end }}