apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "authservice.fullname" . }}-create-key
  labels:
    {{- include "authservice.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    helm.sh/hook-weight: "5"
spec:
  template:
    metadata:
      labels:
        {{- include "authservice.labels" . | nindent 8 }}
        {{- with .Values.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      restartPolicy: Never
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "authservice.fullname" . }}-jwks
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/app/bin/auth-service-token", "--output", "/app/conf/auth_service_jwks"]
          env:
            - name: AUTH_SERVICE_SESSION_SECRET
              value: {{ randAlphaNum 32 | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: temporary
              mountPath: /app/conf
      containers:
        - name: kubectl
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "bitnami/kubectl"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - "kubectl"
            - "create"
            - "secret"
            - "generic"
            - {{ include "authservice.fullname" . }}-key
            - "--from-file"
            - "/app/conf/auth_service_jwks"
          volumeMounts:
            - name: temporary
              readOnly: true
              mountPath: /app/conf
      volumes:
        - name: temporary
          emptyDir: {}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "authservice.fullname" . }}-delete-key
  labels:
    {{- include "authservice.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    helm.sh/hook-weight: "5"
spec:
  template:
    metadata:
      labels:
        {{- include "authservice.labels" . | nindent 8 }}
        {{- with .Values.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      restartPolicy: Never
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "authservice.fullname" . }}-jwks
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: kubectl
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "bitnami/kubectl"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - "kubectl"
            - "delete"
            - "secret"
            - {{ include "authservice.fullname" . }}-key
