apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "authservice.fullname" . }}-jwks
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "1"
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "delete"]