
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "authservice.fullname" . }}-jwks
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "2"
subjects:
  - kind: ServiceAccount
    namespace: {{ .Release.Namespace }}
    name: {{ include "authservice.fullname" . }}-jwks
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "authservice.fullname" . }}-jwks